name: Main

on:
  workflow_dispatch:
    inputs:
      tool:
        required: true
        default: "streamrip"
        type: choice
        options:
          - streamrip
      url:
        required: true

jobs:
  streamrip:
    if: ${{ github.event.inputs.tool == 'streamrip' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          #cache: "pip"

      - name: Install streamrip
        run: pip install git+https://github.com/nathom/streamrip.git@dev

      - name: Rip
        run: |
          rip config
          echo "${{ secrets.STREAMRIP_CONFIG }}" | base64 --decode > /home/runner/.config/streamrip/config.toml
          rip url ${{ github.event.inputs.url }} --no-ansi --no-interaction
